### ISSUE TITLE
[Q] Is the output cached?

### ISSUE THREAD

**Issue by lonix1** [karl-sjogren/robots-txt-middleware#66]
Does this library generate the output once and serve it from memory on every request to `/robots.txt`, or does it regenerate it on every request?

Thanks!

**Comment by karl-sjogren** [comment]
The final output is not cached in the service or middleware, but a `Cache-control` is set to tell the ones retrieving it that it don't need to recheck every time (the default value is 24 hours, but this can be increased using the options object).
