### ISSUE TITLE
Add the option to respond to other robot url's

### ISSUE THREAD

**Issue by anheri** [karl-sjogren/robots-txt-middleware#7]
In my Azure app service i see url on the form /robots843849.txt
so I want to do:
app.UseWhen(httpContext => httpContext.Request.Path.StartsWithSegments("/robots"), builder =>
            {
                builder.UseMiddleware RobotsTxtMiddleware ();
            });

but it does not work because the robots.txt path is hardcoded in the middleware

**Comment by karl-sjogren** [comment]
The robots.txt specification doesn't really allow custom filenames or paths so this doesn't really fit with the library. No real crawler would look for it anywhere except `/robots.txt`.

In your case I would use the [URL Rewriting Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-6.0) to change the request to match the real url if this really is a problem.

Something like this (just adapted from the example on the linked page, not tested)

```csharp
  var options = new RewriteOptions()
    .AddRewrite(@"^robots(.*?)\.txt", "robots.txt", skipRemainingRules: true);

  app.UseRewriter(options);
  app.UseRobotsTxt();
```
