### ISSUE TITLE
robots.txt file not generated

### ISSUE THREAD

**Issue by jeevanthespark** [karl-sjogren/robots-txt-middleware#9]
Hi,
I added the necessary piece of code to configure and use RobotsTxt middleware in my asp.net core application. But when I publish the application, neither can I see robots.txt file generated in application root nor access it via the path /robots.txt when running the app. Could you please provide a sample asp.net core application for reference? I have used the same piece of code as provided in your documentation for testing. Any help would be much appreciated. 
Thanks!

**Comment by karl-sjogren** [comment]
There shouldn't be any files generated, it will be served dynamically when accessing `/robots.txt`. My guess is that you added `app.UseRobotsTxt();` to late in your pipeline (after something that terminates the pipeline like `app.UseEndpoints()`).

This small sample app works fine for me.

```csharp
using RobotsTxt;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddStaticRobotsTxt(builder =>
        builder
            .AddSection(section =>
                section
                    .AddComment("Allow Googlebot")
                    .AddUserAgent("Googlebot")
                    .Allow("/")
                )
    );

var app = builder.Build();

app.MapGet("/", () => "Hello World!");
app.UseRobotsTxt();

app.Run();
```

After that I can access `/robots.txt` and it returns the following.

```
# Allow Googlebot
User-agent: Googlebot
Allow: /
```

**Comment by jeevanthespark** [comment]
Thanks for the explanation. You were right. The middleware was too late in the pipeline. Added it before `app.UseRouting()` and it worked fine. 👍
